services:
  app:
    container_name: program-management
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EMAIL_SERVER: ${EMAIL_SERVER}
        EMAIL_FROM: ${EMAIL_FROM}
        DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ${GCP_SERVICE_ACCOUNT_KEY}:/app/service-account-key.json:ro
    restart: always
    env_file:
      - .env
    ports:
      - "50003:3000"
    mem_limit: 512m
    networks:
      - program-management-network
    depends_on:
      - postgres
      - xite-redis
  # --- PostgreSQL DB ---
  postgres:
    image: postgres:15
    container_name: pm-postgresql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "53001:5432"
    mem_limit: 512m
    networks:
      - program-management-network
  xite-redis:
    image: redis:7
    container_name: xite-redis
    restart: always
    mem_limit: 512m
    volumes:
      - xite_redis_data:/data
    networks:
      - program-management-network
    expose:
      - "6379"
volumes:
  pg_data:
  xite_redis_data:

networks:
  program-management-network:
